const flashcards = [
  {
    verb: "apprendre",
    preposition: "à",
    sentence: "Elle apprend à jouer du piano.",
    translation: "She is learning to play the piano.",
  },
  {
    verb: "essayer",
    preposition: "de",
    sentence: "Il essaie de comprendre la situation.",
    translation: "He is trying to understand the situation.",
  },
  {
    verb: "pouvoir",
    preposition: "neither",
    sentence: "Je peux venir demain.",
    translation: "I can come tomorrow.",
  },
  {
    verb: "commencer",
    preposition: "à",
    sentence: "Ils commencent à travailler tôt.",
    translation: "They start working early.",
  },
  {
    verb: "arrêter",
    preposition: "de",
    sentence: "Elle a arrêté de fumer.",
    translation: "She stopped smoking.",
  },
  {
    verb: "aider",
    preposition: "à",
    sentence: "Je vais t'aider à faire tes devoirs.",
    translation: "I will help you do your homework.",
  },
  {
    verb: "éviter",
    preposition: "de",
    sentence: "Il évite de parler de ce sujet.",
    translation: "He avoids talking about this topic.",
  },
  {
    verb: "vouloir",
    preposition: "neither",
    sentence: "Je veux partir maintenant.",
    translation: "I want to leave now.",
  },
  {
    verb: "s'intéresser",
    preposition: "à",
    sentence: "Elle s'intéresse à l'art moderne.",
    translation: "She is interested in modern art.",
  },
  {
    verb: "finir",
    preposition: "de",
    sentence: "Ils ont fini de préparer le repas.",
    translation: "They finished preparing the meal.",
  },
  {
    verb: "décider",
    preposition: "de",
    sentence: "Nous avons décidé de déménager.",
    translation: "We decided to move.",
  },
  {
    verb: "réussir",
    preposition: "à",
    sentence: "Elle a réussi à obtenir son diplôme.",
    translation: "She succeeded in obtaining her diploma.",
  },
  {
    verb: "penser",
    preposition: "à",
    sentence: "Pense à appeler ta mère.",
    translation: "Remember to call your mother.",
  },
  {
    verb: "oublier",
    preposition: "de",
    sentence: "Il a oublié de fermer la porte.",
    translation: "He forgot to close the door.",
  },
  {
    verb: "avoir besoin",
    preposition: "de",
    sentence: "Nous avons besoin de plus de temps.",
    translation: "We need more time.",
  },
  {
    verb: "continuer",
    preposition: "à",
    sentence: "Elle continue à étudier chaque jour.",
    translation: "She continues studying every day.",
  },
  {
    verb: "s'occuper",
    preposition: "de",
    sentence: "Je m'occupe de l'organisation.",
    translation: "I am in charge of the organization.",
  },
  {
    verb: "se souvenir",
    preposition: "de",
    sentence: "Elle se souvient de son enfance.",
    translation: "She remembers her childhood.",
  },
  {
    verb: "se préparer",
    preposition: "à",
    sentence: "Ils se préparent à partir.",
    translation: "They are preparing to leave.",
  },
  {
    verb: "choisir",
    preposition: "de",
    sentence: "Il a choisi de rester.",
    translation: "He chose to stay.",
  },
  {
    verb: "promettre",
    preposition: "de",
    sentence: "Elle a promis de revenir bientôt.",
    translation: "She promised to return soon.",
  },
  {
    verb: "s'amuser",
    preposition: "à",
    sentence: "Ils s'amusent à jouer au football.",
    translation: "They have fun playing football.",
  },
  {
    verb: "tenir",
    preposition: "à",
    sentence: "Je tiens à te remercier.",
    translation: "I insist on thanking you.",
  },
  {
    verb: "attendre",
    preposition: "neither",
    sentence: "Nous attendons le bus.",
    translation: "We are waiting for the bus.",
  },
  {
    verb: "chercher",
    preposition: "neither",
    sentence: "Il cherche ses clés.",
    translation: "He is looking for his keys.",
  },
  {
    verb: "regarder",
    preposition: "neither",
    sentence: "Elle regarde la télévision.",
    translation: "She is watching television.",
  },
  {
    verb: "écouter",
    preposition: "neither",
    sentence: "Ils écoutent de la musique.",
    translation: "They are listening to music.",
  },
  {
    verb: "s'habituer",
    preposition: "à",
    sentence: "Elle s'habitue à sa nouvelle maison.",
    translation: "She is getting used to her new home.",
  },
  {
    verb: "refuser",
    preposition: "de",
    sentence: "Il a refusé de partir.",
    translation: "He refused to leave.",
  },
  {
    verb: "prier",
    preposition: "de",
    sentence: "Je vous prie de m'excuser.",
    translation: "I beg your pardon.",
  },
  {
    verb: "dépendre",
    preposition: "de",
    sentence: "Cela dépend de toi.",
    translation: "That depends on you.",
  },
  {
    verb: "hésiter",
    preposition: "à",
    sentence: "Elle hésite à accepter l'offre.",
    translation: "She hesitates to accept the offer.",
  },
  {
    verb: "forcer",
    preposition: "à",
    sentence: "On l'a forcé à travailler plus dur.",
    translation: "He was forced to work harder.",
  },
  {
    verb: "inviter",
    preposition: "à",
    sentence: "Ils nous ont invités à dîner.",
    translation: "They invited us to dinner.",
  },
  {
    verb: "permettre",
    preposition: "de",
    sentence: "Elle permet aux enfants de jouer dehors.",
    translation: "She allows the children to play outside.",
  },
  {
    verb: "interdire",
    preposition: "de",
    sentence: "Il m'a interdit de conduire sa voiture.",
    translation: "He forbade me to drive his car.",
  },
  {
    verb: "se décider",
    preposition: "à",
    sentence: "Elle s'est décidée à changer de carrière.",
    translation: "She decided to change careers.",
  },
  {
    verb: "renoncer",
    preposition: "à",
    sentence: "Il a renoncé à fumer.",
    translation: "He gave up smoking.",
  },
  {
    verb: "s'attendre",
    preposition: "à",
    sentence: "Nous nous attendons à une réponse rapide.",
    translation: "We are expecting a quick response.",
  },
  {
    verb: "craindre",
    preposition: "de",
    sentence: "Elle craint de perdre son emploi.",
    translation: "She is afraid of losing her job.",
  },
  {
    verb: "rêver",
    preposition: "de",
    sentence: "Il rêve de devenir acteur.",
    translation: "He dreams of becoming an actor.",
  },
  {
    verb: "aimer",
    preposition: "neither",
    sentence: "J'aime voyager.",
    translation: "I love traveling.",
  },
  {
    verb: "adorer",
    preposition: "neither",
    sentence: "Elle adore cuisiner.",
    translation: "She loves cooking.",
  },
  {
    verb: "détester",
    preposition: "neither",
    sentence: "Ils détestent les araignées.",
    translation: "They hate spiders.",
  },
  {
    verb: "espérer",
    preposition: "neither",
    sentence: "Il espère réussir l'examen.",
    translation: "He hopes to pass the exam.",
  },
  {
    verb: "oser",
    preposition: "neither",
    sentence: "Elle n'ose pas lui parler.",
    translation: "She doesn't dare to speak to him.",
  },
  {
    verb: "sembler",
    preposition: "neither",
    sentence: "Il semble fatigué.",
    translation: "He seems tired.",
  },
  {
    verb: "affirmer",
    preposition: "neither",
    sentence: "Elle affirme connaître la vérité.",
    translation: "She claims to know the truth.",
  },
  {
    verb: "désirer",
    preposition: "neither",
    sentence: "Il désire voyager en Europe.",
    translation: "He wants to travel in Europe.",
  },
  {
    verb: "paraître",
    preposition: "neither",
    sentence: "Elle paraît heureuse.",
    translation: "She appears happy.",
  },
  {
    verb: "préférer",
    preposition: "neither",
    sentence: "Nous préférons rester ici.",
    translation: "We prefer to stay here.",
  },
  {
    verb: "valoir mieux",
    preposition: "neither",
    sentence: "Il vaut mieux partir tôt.",
    translation: "It's better to leave early.",
  },
  {
    verb: "arriver",
    preposition: "à",
    sentence: "Il est arrivé à comprendre le problème.",
    translation: "He managed to understand the problem.",
  },
  {
    verb: "recommencer",
    preposition: "à",
    sentence: "Elle a dû recommencer à zéro.",
    translation: "She had to start over.",
  },
  {
    verb: "échapper",
    preposition: "à",
    sentence: "Il a réussi à échapper à la police.",
    translation: "He managed to escape the police.",
  },
  {
    verb: "croire",
    preposition: "neither",
    sentence: "Je crois qu'il a raison.",
    translation: "I think he's right.",
  },
  {
    verb: "exiger",
    preposition: "de",
    sentence: "Le professeur exige de ses élèves qu'ils fassent des efforts.",
    translation: "The teacher demands that his students make efforts.",
  },
  {
    verb: "risquer",
    preposition: "de",
    sentence: "Elle risque de perdre son emploi.",
    translation: "She risks losing her job.",
  },
  {
    verb: "venir",
    preposition: "de",
    sentence: "Ils viennent de terminer leur projet.",
    translation: "They have just finished their project.",
  },
  {
    verb: "jouer",
    preposition: "à",
    sentence: "Les enfants jouent à cache-cache.",
    translation: "The children are playing hide and seek.",
  },
  {
    verb: "demander",
    preposition: "à",
    sentence: "Il a demandé à son ami de l'aider.",
    translation: "He asked his friend to help him.",
  },
  {
    verb: "se mettre",
    preposition: "à",
    sentence: "Elle se met à pleurer quand elle est triste.",
    translation: "She starts crying when she is sad.",
  },
  {
    verb: "commander",
    preposition: "de",
    sentence: "Il a commandé de nouveaux produits en ligne.",
    translation: "He ordered new products online.",
  },
  {
    verb: "faire semblant",
    preposition: "de",
    sentence: "Il fait semblant de dormir.",
    translation: "He pretends to be sleeping.",
  },
  {
    verb: "accepter",
    preposition: "de",
    sentence: "Elle a accepté de travailler le week-end.",
    translation: "She agreed to work on the weekend.",
  },
  {
    verb: "prêter",
    preposition: "à",
    sentence: "Il prête son livre à son ami.",
    translation: "He lends his book to his friend.",
  },
  {
    verb: "emprunter",
    preposition: "de",
    sentence: "Elle a emprunté de l'argent à la banque.",
    translation: "She borrowed money from the bank.",
  },
  {
    verb: "tenter",
    preposition: "de",
    sentence: "Il tente de résoudre ce problème.",
    translation: "He is trying to solve this problem.",
  },
  {
    verb: "être prêt",
    preposition: "à",
    sentence: "Elle est prête à partir.",
    translation: "She is ready to leave.",
  },
  {
    verb: "défendre",
    preposition: "de",
    sentence: "Ils défendent leurs droits.",
    translation: "They defend their rights.",
  },
  {
    verb: "pardonner",
    preposition: "de",
    sentence: "Il a pardonné de tout son cœur.",
    translation: "He forgave with all his heart.",
  },
  {
    verb: "féliciter",
    preposition: "de",
    sentence: "Elle félicite son fils de ses réussites.",
    translation: "She congratulates her son on his successes.",
  },
  {
    verb: "avoir peur",
    preposition: "de",
    sentence: "Il a peur de parler en public.",
    translation: "He is afraid of speaking in public.",
  },
  {
    verb: "mentir",
    preposition: "à",
    sentence: "Elle a menti à ses parents.",
    translation: "She lied to her parents.",
  },
  {
    verb: "servir",
    preposition: "à",
    sentence: "Cet outil sert à couper le bois.",
    translation: "This tool is used for cutting wood.",
  },
  {
    verb: "s'approcher",
    preposition: "de",
    sentence: "Elle s'approche de la sortie.",
    translation: "She is approaching the exit.",
  },
  {
    verb: "conseiller",
    preposition: "de",
    sentence: "Je te conseille de prendre le train.",
    translation: "I advise you to take the train.",
  },
  {
    verb: "jurer",
    preposition: "de",
    sentence: "Il a juré de dire la vérité.",
    translation: "He swore to tell the truth.",
  },
  {
    verb: "s'efforcer",
    preposition: "de",
    sentence: "Elle s'efforce de bien faire.",
    translation: "She strives to do well.",
  },
  {
    verb: "rappeler",
    preposition: "de",
    sentence: "Il doit rappeler de fermer la porte.",
    translation: "He must remember to close the door.",
  },
  {
    verb: "pardonner",
    preposition: "à",
    sentence: "Elle a pardonné à son frère.",
    translation: "She forgave her brother.",
  },
  {
    verb: "s'abstenir",
    preposition: "de",
    sentence: "Ils s'abstiennent de voter.",
    translation: "They abstain from voting.",
  },
  {
    verb: "approuver",
    preposition: "neither",
    sentence: "Elle approuve cette décision.",
    translation: "She approves of this decision.",
  },
  {
    verb: "réagir",
    preposition: "à",
    sentence: "Il a réagi à la nouvelle.",
    translation: "He reacted to the news.",
  },
  {
    verb: "téléphoner",
    preposition: "à",
    sentence: "Elle téléphone à son ami tous les jours.",
    translation: "She calls her friend every day.",
  },
  {
    verb: "s'engager",
    preposition: "à",
    sentence: "Il s'engage à respecter les règles.",
    translation: "He commits to following the rules.",
  },
  {
    verb: "autoriser",
    preposition: "à",
    sentence: "Ils l'ont autorisé à entrer.",
    translation: "They allowed him to enter.",
  },
  {
    verb: "imposer",
    preposition: "de",
    sentence: "Le chef impose de nouvelles règles.",
    translation: "The boss imposes new rules.",
  },
  {
    verb: "applaudir",
    preposition: "neither",
    sentence: "Le public applaudit le spectacle.",
    translation: "The audience applauds the performance.",
  },
  {
    verb: "réclamer",
    preposition: "neither",
    sentence: "Elle réclame justice.",
    translation: "She demands justice.",
  },
  {
    verb: "vérifier",
    preposition: "neither",
    sentence: "Il vérifie ses réponses.",
    translation: "He checks his answers.",
  },
  {
    verb: "diriger",
    preposition: "neither",
    sentence: "Elle dirige une équipe de développeurs.",
    translation: "She leads a team of developers.",
  },
  {
    verb: "assurer",
    preposition: "neither",
    sentence: "Il assure le bon déroulement du projet.",
    translation: "He ensures the smooth running of the project.",
  },
];

export default flashcards;
