const flashcards = [
  {
    number: 1,
    verb: "apprendre",
    preposition: "à",
    sentence: "Elle apprend à jouer du piano.",
    translation: "She is learning to play the piano.",
  },
  {
    number: 2,
    verb: "essayer",
    preposition: "de",
    sentence: "Il essaie de comprendre la situation.",
    translation: "He is trying to understand the situation.",
  },
  {
    number: 3,
    verb: "pouvoir",
    preposition: "neither",
    sentence: "Je peux venir demain.",
    translation: "I can come tomorrow.",
  },
  {
    number: 4,
    verb: "commencer",
    preposition: "à",
    sentence: "Ils commencent à travailler tôt.",
    translation: "They start working early.",
  },
  {
    number: 5,
    verb: "arrêter",
    preposition: "de",
    sentence: "Elle a arrêté de fumer.",
    translation: "She stopped smoking.",
  },
  {
    number: 6,
    verb: "aider",
    preposition: "à",
    sentence: "Je vais t'aider à faire tes devoirs.",
    translation: "I will help you do your homework.",
  },
  {
    number: 7,
    verb: "éviter",
    preposition: "de",
    sentence: "Il évite de parler de ce sujet.",
    translation: "He avoids talking about this topic.",
  },
  {
    number: 8,
    verb: "vouloir",
    preposition: "neither",
    sentence: "Je veux partir maintenant.",
    translation: "I want to leave now.",
  },
  {
    number: 9,
    verb: "s'intéresser",
    preposition: "à",
    sentence: "Elle s'intéresse à l'art moderne.",
    translation: "She is interested in modern art.",
  },
  {
    number: 10,
    verb: "finir",
    preposition: "de",
    sentence: "Ils ont fini de préparer le repas.",
    translation: "They finished preparing the meal.",
  },
  {
    number: 11,
    verb: "décider",
    preposition: "de",
    sentence: "Nous avons décidé de déménager.",
    translation: "We decided to move.",
  },
  {
    number: 12,
    verb: "réussir",
    preposition: "à",
    sentence: "Elle a réussi à obtenir son diplôme.",
    translation: "She succeeded in obtaining her diploma.",
  },
  {
    number: 13,
    verb: "penser",
    preposition: "à",
    sentence: "Pense à appeler ta mère.",
    translation: "Remember to call your mother.",
  },
  {
    number: 14,
    verb: "oublier",
    preposition: "de",
    sentence: "Il a oublié de fermer la porte.",
    translation: "He forgot to close the door.",
  },
  {
    number: 15,
    verb: "avoir besoin",
    preposition: "de",
    sentence: "Nous avons besoin de plus de temps.",
    translation: "We need more time.",
  },
  {
    number: 16,
    verb: "continuer",
    preposition: "à",
    sentence: "Elle continue à étudier chaque jour.",
    translation: "She continues studying every day.",
  },
  {
    number: 17,
    verb: "s'occuper",
    preposition: "de",
    sentence: "Je m'occupe de l'organisation.",
    translation: "I am in charge of the organization.",
  },
  {
    number: 18,
    verb: "se souvenir",
    preposition: "de",
    sentence: "Elle se souvient de son enfance.",
    translation: "She remembers her childhood.",
  },
  {
    number: 19,
    verb: "se préparer",
    preposition: "à",
    sentence: "Ils se préparent à partir.",
    translation: "They are preparing to leave.",
  },
  {
    number: 20,
    verb: "choisir",
    preposition: "de",
    sentence: "Il a choisi de rester.",
    translation: "He chose to stay.",
  },
  {
    number: 21,
    verb: "promettre",
    preposition: "de",
    sentence: "Elle a promis de revenir bientôt.",
    translation: "She promised to return soon.",
  },
  {
    number: 22,
    verb: "s'amuser",
    preposition: "à",
    sentence: "Ils s'amusent à jouer au football.",
    translation: "They have fun playing football.",
  },
  {
    number: 23,
    verb: "tenir",
    preposition: "à",
    sentence: "Je tiens à te remercier.",
    translation: "I insist on thanking you.",
  },
  {
    number: 24,
    verb: "attendre",
    preposition: "neither",
    sentence: "Nous attendons le bus.",
    translation: "We are waiting for the bus.",
  },
  {
    number: 25,
    verb: "chercher",
    preposition: "neither",
    sentence: "Il cherche ses clés.",
    translation: "He is looking for his keys.",
  },
  {
    number: 26,
    verb: "regarder",
    preposition: "neither",
    sentence: "Elle regarde la télévision.",
    translation: "She is watching television.",
  },
  {
    number: 27,
    verb: "écouter",
    preposition: "neither",
    sentence: "Ils écoutent de la musique.",
    translation: "They are listening to music.",
  },
  {
    number: 28,
    verb: "s'habituer",
    preposition: "à",
    sentence: "Elle s'habitue à sa nouvelle maison.",
    translation: "She is getting used to her new home.",
  },
  {
    number: 29,
    verb: "refuser",
    preposition: "de",
    sentence: "Il a refusé de partir.",
    translation: "He refused to leave.",
  },
  {
    number: 30,
    verb: "prier",
    preposition: "de",
    sentence: "Je vous prie de m'excuser.",
    translation: "I beg your pardon.",
  },
  {
    number: 31,
    verb: "dépendre",
    preposition: "de",
    sentence: "Cela dépend de toi.",
    translation: "That depends on you.",
  },
  {
    number: 32,
    verb: "hésiter",
    preposition: "à",
    sentence: "Elle hésite à accepter l'offre.",
    translation: "She hesitates to accept the offer.",
  },
  {
    number: 33,
    verb: "forcer",
    preposition: "à",
    sentence: "On l'a forcé à travailler plus dur.",
    translation: "He was forced to work harder.",
  },
  {
    number: 34,
    verb: "inviter",
    preposition: "à",
    sentence: "Ils nous ont invités à dîner.",
    translation: "They invited us to dinner.",
  },
  {
    number: 35,
    verb: "permettre",
    preposition: "de",
    sentence: "Elle permet aux enfants de jouer dehors.",
    translation: "She allows the children to play outside.",
  },
  {
    number: 36,
    verb: "interdire",
    preposition: "de",
    sentence: "Il m'a interdit de conduire sa voiture.",
    translation: "He forbade me to drive his car.",
  },
  {
    number: 37,
    verb: "se décider",
    preposition: "à",
    sentence: "Elle s'est décidée à changer de carrière.",
    translation: "She decided to change careers.",
  },
  {
    number: 38,
    verb: "renoncer",
    preposition: "à",
    sentence: "Il a renoncé à fumer.",
    translation: "He gave up smoking.",
  },
  {
    number: 39,
    verb: "s'attendre",
    preposition: "à",
    sentence: "Nous nous attendons à une réponse rapide.",
    translation: "We are expecting a quick response.",
  },
  {
    number: 40,
    verb: "craindre",
    preposition: "de",
    sentence: "Elle craint de perdre son emploi.",
    translation: "She is afraid of losing her job.",
  },
  {
    number: 41,
    verb: "rêver",
    preposition: "de",
    sentence: "Il rêve de devenir acteur.",
    translation: "He dreams of becoming an actor.",
  },
  {
    number: 42,
    verb: "aimer",
    preposition: "neither",
    sentence: "J'aime voyager.",
    translation: "I love traveling.",
  },
  {
    number: 43,
    verb: "adorer",
    preposition: "neither",
    sentence: "Elle adore cuisiner.",
    translation: "She loves cooking.",
  },
  {
    number: 44,
    verb: "détester",
    preposition: "neither",
    sentence: "Ils détestent les araignées.",
    translation: "They hate spiders.",
  },
  {
    number: 45,
    verb: "espérer",
    preposition: "neither",
    sentence: "Il espère réussir l'examen.",
    translation: "He hopes to pass the exam.",
  },
  {
    number: 46,
    verb: "oser",
    preposition: "neither",
    sentence: "Elle n'ose pas lui parler.",
    translation: "She doesn't dare to speak to him.",
  },
  {
    number: 47,
    verb: "sembler",
    preposition: "neither",
    sentence: "Il semble fatigué.",
    translation: "He seems tired.",
  },
  {
    number: 48,
    verb: "affirmer",
    preposition: "neither",
    sentence: "Elle affirme connaître la vérité.",
    translation: "She claims to know the truth.",
  },
  {
    number: 49,
    verb: "désirer",
    preposition: "neither",
    sentence: "Il désire voyager en Europe.",
    translation: "He wants to travel in Europe.",
  },
  {
    number: 50,
    verb: "paraître",
    preposition: "neither",
    sentence: "Elle paraît heureuse.",
    translation: "She appears happy.",
  },
  {
    number: 51,
    verb: "préférer",
    preposition: "neither",
    sentence: "Nous préférons rester ici.",
    translation: "We prefer to stay here.",
  },
  {
    number: 52,
    verb: "valoir mieux",
    preposition: "neither",
    sentence: "Il vaut mieux partir tôt.",
    translation: "It's better to leave early.",
  },
  {
    number: 53,
    verb: "arriver",
    preposition: "à",
    sentence: "Il est arrivé à comprendre le problème.",
    translation: "He managed to understand the problem.",
  },
  {
    number: 54,
    verb: "recommencer",
    preposition: "à",
    sentence: "Elle a dû recommencer à zéro.",
    translation: "She had to start over.",
  },
  {
    number: 55,
    verb: "échapper",
    preposition: "à",
    sentence: "Il a réussi à échapper à la police.",
    translation: "He managed to escape the police.",
  },
  {
    number: 56,
    verb: "croire",
    preposition: "neither",
    sentence: "Je crois qu'il a raison.",
    translation: "I think he's right.",
  },
  {
    number: 57,
    verb: "exiger",
    preposition: "de",
    sentence: "Le professeur exige de ses élèves qu'ils fassent des efforts.",
    translation: "The teacher demands that his students make efforts.",
  },
  {
    number: 58,
    verb: "risquer",
    preposition: "de",
    sentence: "Elle risque de perdre son emploi.",
    translation: "She risks losing her job.",
  },
  {
    number: 59,
    verb: "venir",
    preposition: "de",
    sentence: "Ils viennent de terminer leur projet.",
    translation: "They have just finished their project.",
  },
  {
    number: 60,
    verb: "jouer",
    preposition: "à",
    sentence: "Les enfants jouent à cache-cache.",
    translation: "The children are playing hide and seek.",
  },
  {
    number: 61,
    verb: "demander",
    preposition: "à",
    sentence: "Il a demandé à son ami de l'aider.",
    translation: "He asked his friend to help him.",
  },
  {
    number: 62,
    verb: "se mettre",
    preposition: "à",
    sentence: "Elle se met à pleurer quand elle est triste.",
    translation: "She starts crying when she is sad.",
  },
  {
    number: 63,
    verb: "commander",
    preposition: "de",
    sentence: "Il a commandé de nouveaux produits en ligne.",
    translation: "He ordered new products online.",
  },
  {
    number: 64,
    verb: "faire semblant",
    preposition: "de",
    sentence: "Il fait semblant de dormir.",
    translation: "He pretends to be sleeping.",
  },
  {
    number: 65,
    verb: "accepter",
    preposition: "de",
    sentence: "Elle a accepté de travailler le week-end.",
    translation: "She agreed to work on the weekend.",
  },
  {
    number: 66,
    verb: "prêter",
    preposition: "à",
    sentence: "Il prête son livre à son ami.",
    translation: "He lends his book to his friend.",
  },
  {
    number: 67,
    verb: "emprunter",
    preposition: "de",
    sentence: "Elle a emprunté de l'argent à la banque.",
    translation: "She borrowed money from the bank.",
  },
  {
    number: 68,
    verb: "tenter",
    preposition: "de",
    sentence: "Il tente de résoudre ce problème.",
    translation: "He is trying to solve this problem.",
  },
  {
    number: 69,
    verb: "être prêt",
    preposition: "à",
    sentence: "Elle est prête à partir.",
    translation: "She is ready to leave.",
  },
  {
    number: 70,
    verb: "défendre",
    preposition: "de",
    sentence: "Ils défendent leurs droits.",
    translation: "They defend their rights.",
  },
  {
    number: 71,
    verb: "pardonner",
    preposition: "de",
    sentence: "Il a pardonné de tout son cœur.",
    translation: "He forgave with all his heart.",
  },
  {
    number: 72,
    verb: "féliciter",
    preposition: "de",
    sentence: "Elle félicite son fils de ses réussites.",
    translation: "She congratulates her son on his successes.",
  },
  {
    number: 73,
    verb: "avoir peur",
    preposition: "de",
    sentence: "Il a peur de parler en public.",
    translation: "He is afraid of speaking in public.",
  },
  {
    number: 74,
    verb: "mentir",
    preposition: "à",
    sentence: "Elle a menti à ses parents.",
    translation: "She lied to her parents.",
  },
  {
    number: 75,
    verb: "servir",
    preposition: "à",
    sentence: "Cet outil sert à couper le bois.",
    translation: "This tool is used for cutting wood.",
  },
  {
    number: 76,
    verb: "s'approcher",
    preposition: "de",
    sentence: "Elle s'approche de la sortie.",
    translation: "She is approaching the exit.",
  },
  {
    number: 77,
    verb: "conseiller",
    preposition: "de",
    sentence: "Je te conseille de prendre le train.",
    translation: "I advise you to take the train.",
  },
  {
    number: 78,
    verb: "jurer",
    preposition: "de",
    sentence: "Il a juré de dire la vérité.",
    translation: "He swore to tell the truth.",
  },
  {
    number: 79,
    verb: "s'efforcer",
    preposition: "de",
    sentence: "Elle s'efforce de bien faire.",
    translation: "She strives to do well.",
  },
  {
    number: 80,
    verb: "rappeler",
    preposition: "de",
    sentence: "Il doit rappeler de fermer la porte.",
    translation: "He must remember to close the door.",
  },
  {
    number: 81,
    verb: "pardonner",
    preposition: "à",
    sentence: "Elle a pardonné à son frère.",
    translation: "She forgave her brother.",
  },
  {
    number: 82,
    verb: "s'abstenir",
    preposition: "de",
    sentence: "Ils s'abstiennent de voter.",
    translation: "They abstain from voting.",
  },
  {
    number: 83,
    verb: "approuver",
    preposition: "neither",
    sentence: "Elle approuve cette décision.",
    translation: "She approves of this decision.",
  },
  {
    number: 84,
    verb: "réagir",
    preposition: "à",
    sentence: "Il a réagi à la nouvelle.",
    translation: "He reacted to the news.",
  },
  {
    number: 85,
    verb: "téléphoner",
    preposition: "à",
    sentence: "Elle téléphone à son ami tous les jours.",
    translation: "She calls her friend every day.",
  },
  {
    number: 86,
    verb: "s'engager",
    preposition: "à",
    sentence: "Il s'engage à respecter les règles.",
    translation: "He commits to following the rules.",
  },
  {
    number: 87,
    verb: "autoriser",
    preposition: "à",
    sentence: "Ils l'ont autorisé à entrer.",
    translation: "They allowed him to enter.",
  },
  {
    number: 88,
    verb: "imposer",
    preposition: "de",
    sentence: "Le chef impose de nouvelles règles.",
    translation: "The boss imposes new rules.",
  },
  {
    number: 89,
    verb: "applaudir",
    preposition: "neither",
    sentence: "Le public applaudit le spectacle.",
    translation: "The audience applauds the performance.",
  },
  {
    number: 90,
    verb: "réclamer",
    preposition: "neither",
    sentence: "Elle réclame justice.",
    translation: "She demands justice.",
  },
  {
    number: 91,
    verb: "vérifier",
    preposition: "neither",
    sentence: "Il vérifie ses réponses.",
    translation: "He checks his answers.",
  },
  {
    number: 92,
    verb: "diriger",
    preposition: "neither",
    sentence: "Elle dirige une équipe de développeurs.",
    translation: "She leads a team of developers.",
  },
  {
    number: 93,
    verb: "assurer",
    preposition: "neither",
    sentence: "Il assure le bon déroulement du projet.",
    translation: "He ensures the smooth running of the project.",
  },
  {
    number: 94,
    verb: "répondre",
    preposition: "à",
    sentence: "Il a répondu à toutes les questions.",
    translation: "He answered all the questions.",
  },
  {
    number: 95,
    verb: "vivre",
    preposition: "neither",
    sentence: "Elle vit à Paris depuis trois ans.",
    translation: "She has lived in Paris for three years.",
  },
  {
    number: 96,
    verb: "utiliser",
    preposition: "neither",
    sentence: "Ils utilisent un logiciel pour gérer leurs finances.",
    translation: "They use software to manage their finances.",
  },
  {
    number: 97,
    verb: "travailler",
    preposition: "neither",
    sentence: "Elle travaille dans une entreprise internationale.",
    translation: "She works in an international company.",
  },
  {
    number: 98,
    verb: "lutter",
    preposition: "contre",
    sentence: "Ils luttent contre les inégalités sociales.",
    translation: "They fight against social inequalities.",
  },
  {
    number: 99,
    verb: "encourager",
    preposition: "à",
    sentence: "Nous encourageons nos enfants à lire davantage.",
    translation: "We encourage our children to read more.",
  },
  {
    number: 100,
    verb: "consacrer",
    preposition: "à",
    sentence: "Il consacre du temps à sa famille le week-end.",
    translation: "He dedicates time to his family on weekends.",
  },
  {
    number: 101,
    verb: "supporter",
    preposition: "neither",
    sentence: "Elle ne supporte pas le bruit.",
    translation: "She can't stand the noise.",
  },
  {
    number: 102,
    verb: "examiner",
    preposition: "neither",
    sentence: "Ils examinent les documents avant de signer.",
    translation: "They examine the documents before signing.",
  },
  {
    number: 103,
    verb: "gagner",
    preposition: "neither",
    sentence: "Elle gagne bien sa vie.",
    translation: "She earns a good living.",
  },
  {
    number: 104,
    verb: "participer",
    preposition: "à",
    sentence: "Il participe à une conférence chaque année.",
    translation: "He participates in a conference every year.",
  },
  {
    number: 105,
    verb: "construire",
    preposition: "neither",
    sentence: "Ils construisent une nouvelle maison.",
    translation: "They are building a new house.",
  },
  {
    number: 106,
    verb: "détruire",
    preposition: "neither",
    sentence: "La tempête a détruit plusieurs maisons.",
    translation: "The storm destroyed several houses.",
  },
  {
    number: 107,
    verb: "obéir",
    preposition: "à",
    sentence: "Les soldats obéissent aux ordres.",
    translation: "The soldiers obey orders.",
  },
  {
    number: 108,
    verb: "confier",
    preposition: "à",
    sentence: "Elle a confié ses enfants à sa sœur.",
    translation: "She entrusted her children to her sister.",
  },
  {
    number: 109,
    verb: "appartenir",
    preposition: "à",
    sentence: "Ce livre appartient à mon ami.",
    translation: "This book belongs to my friend.",
  },
  {
    number: 110,
    verb: "prévenir",
    preposition: "de",
    sentence: "Elle a prévenu son collègue de son absence.",
    translation: "She informed her colleague of her absence.",
  },
  {
    number: 111,
    verb: "rencontrer",
    preposition: "neither",
    sentence: "Ils se sont rencontrés dans un café.",
    translation: "They met in a café.",
  },
  {
    number: 112,
    verb: "fournir",
    preposition: "neither",
    sentence: "L'entreprise fournit des équipements de bureau.",
    translation: "The company provides office supplies.",
  },
  {
    number: 113,
    verb: "vendre",
    preposition: "neither",
    sentence: "Ils vendent des produits biologiques.",
    translation: "They sell organic products.",
  },
];

export default flashcards;
